openapi: 3.1.0
info:
  version: 1.0.0
  title: TAIS Backend API
  termsOfService: https://example.com/terms/
  contact:
    name: Suresh Kumar Mukhiya
    email: itsmeskm99@gmail.com
    url: https://www.skmukhiya.com.np
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: "https://www.tryg.no/themes/trygno/assets/svg/tryg-logo.svg"
    altText: Tryg Logo
  description: >
    This is the API for the TAIS Backend.

    # Introduction

    This API definition is intended to to be a good starting point for
    describing your API in [OpenAPI/Swagger
    format](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md).

tags:
  - name: Project
    description: "Project related operations."
  - name: SonarQube
    description: "SonarQube reports and analysis."
  - name: CI/CD
    description: "CI/CD pipelines, statistics, and dependencies."
  - name: User
    description: "User related operations."
  - name: Tag
    description: "Tag related operations."
x-tagGroups:
  - name: General
    tags:
      - Project
      - SonarQube
      - CI/CD
      - Echo
servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://example.com/api/v1
paths:
  "/users/{username}":
    $ref: "paths/users_{username}.yaml"
  "/user":
    $ref: "paths/user.yaml"
  "/user/list":
    $ref: "paths/user-status.yaml"
  /pathItem:
    $ref: paths/pathItem.yaml
  /pathItemWithExamples:
    $ref: paths/pathItemWithExamples.yaml
  "/echo":
    $ref: "paths/echo.yaml"
  "/projects":
    $ref: "paths/projects.yaml"
  "/projects/{id}":
    $ref: "paths/projects_{id}.yaml"
  "/projects/{projectId}/sonarqube-reports":
    $ref: "paths/projects_{projectId}_sonarqube-reports.yaml"
  "/cicd/projects/{projectId}/pipelines":
    $ref: "paths/cicd_projects_{projectId}_pipelines.yaml"
  "/cicd/projects/{projectId}/pipelines/{pipelineId}/retry":
    $ref: "paths/cicd_projects_{projectId}_pipelines_{pipelineId}_retry.yaml"
  "/cicd/projects/{projectId}/statistics":
    $ref: "paths/cicd_projects_{projectId}_statistics.yaml"
  "/cicd/projects/{projectId}/dependencies":
    $ref: "paths/cicd_projects_{projectId}_dependencies.yaml"
  "/cicd/projects/{projectId}/commits":
    $ref: "paths/cicd_projects_{projectId}_commits.yaml"
components:
  securitySchemes:
    main_auth:
      description: "Example description text of the OAuth2 scheme."
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            "read:users": read user info
            "write:users": modify or remove users
    api_key:
      description: "Example description text of the API key scheme."
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
